BIN = mandelbrot
CC = gcc
CFLAGS = -DNDEBUG -Ofast -fomit-frame-pointer -Wall -pedantic 
LIBS = -Wall -lopengl32 -lglfw3 -lgdi32 -lglew32 -lglu32 -lm
SRC = src/main.c src/GLutils.c

all:
	${CC} ${CFLAGS} -o ${BIN} ${SRC} ${LIBS}