BIN = mandelbrot
CC = gcc
CFLAGS = -DNDEBUG -Ofast -fomit-frame-pointer -Wall -pedantic -march=znver1
LIBS = -Wall -lopengl32 -lglfw3 -lgdi32 -lglew32 -lglu32 -lm
SRC = main.c GLutils.c

all:
	${CC} ${CFLAGS} -o ${BIN} ${SRC} ${LIBS}